services:
  database:
    image: postgres:latest
    container_name: admin4tutor-db
    environment: 
      POSTGRES_USER: silent_rider
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tutor_manager_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - admin4tutor-network

  server:
    build:
      context: ./server
    container_name: admin4tutor-server
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/tutor_manager_db
      SPRING_DATASOURCE_USERNAME: silent_rider
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - admin4tutor-network

  bot:
    build:
      context: ./bot
    container_name: admin4tutor-bot
    environment:
      SPRING_PROFILES_ACTIVE: docker
      TELEGRAM_BOT_USERNAME: tutormanager_bot
      TELEGRAM_BOT_TOKEN: 7869551904:AAEh6CK_NBfY2H8k8emkfIqV6d5aA25SEic
      SERVER_API_URL: http://server:8080
    networks:
      - admin4tutor-network

networks:
  admin4tutor-network:

volumes:
  db_data: