#Application name
spring.application.name=admin4tutor
#Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/tutor_manager_db
spring.datasource.username=silent_rider
spring.datasource.password=password
#Database settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Logging adjusting
logging.file.name=logs/history.log
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %level - %msg%n

