spring.application.name=admin4tutor
spring.datasource.url=jdbc:postgresql://localhost:5432/application
spring.datasource.username=silent_rider
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
