package com.admin4tutor.bot.service;

public enum Stage {
    ASKING_FOR_ROLE,
    CHOOSING_LANGUAGE,
    PLANNING_SCHEDULE,
    ASKING_FOR_NAME,
    ASKING_FOR_EMAIL,
    ASKING_FOR_PHONE_NUMBER,
    ASKING_FOR_AVAILABILITY,
    ASKING_FOR_BIOGRAPHY
}