package com.admin4tutor.bot.service;

public enum Stage {
    ASKING_FOR_ROLE,
    ASKING_FOR_LANGUAGE,
    ASKING_FOR_NAME,
    ASKING_FOR_DATE_OF_BIRTH,
    ASKING_FOR_AVAILABILITY_DAY,
    ASKING_FOR_AVAILABILITY_INTERVALS,
    ASKING_FOR_ANOTHER_AVAILABILITY_DAY,
    ASKING_FOR_PRICE,
    ASKING_FOR_SCHEDULE_DAY,
    ASKING_FOR_SCHEDULE_TIME,
    ASKING_FOR_ANOTHER_SCHEDULE_DAY,
    ASKING_FOR_TUTOR,
    VIEWING_TUTOR_PAGE,
    ASKING_FOR_EMAIL,
    ASKING_FOR_PHONE_NUMBER,
    ASKING_FOR_BIOGRAPHY,
    CREATED_ACCOUNT
}